# Generated by Django 4.0.3 on 2022-03-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_kz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_kz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
